version: "3"

services:
    api:
        command: >
            sh -c "sleep 10 &&
                    mkdir -p reports &&
                    npm run test:func > ./reports/report.txt"
        ports:
            - 80:80
        environment:
            PORT: 80
