version: "3"

services:
    api:
        command: npm run prod
        ports:
            - 80:80
        environment:
            PORT: 80

    es:
        volumes:
            - ./data/es:/usr/share/elasticsearch/data
